services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - .env'
    command: npm start
    networks:
      - orchestration_net
      - backend_net
networks:
  orchestration_net:
    external: true
  backend_net:
    external: true
